export const GET_QUERY_RESULTS_START = "GET-QUERY-RESULTS-START";
export const GET_QUERY_RESULTS_SUCCESS = "GET-QUERY-RESULTS-SUCCESS";
export const GET_QUERY_RESULTS_FAILURE = "GET-QUERY-RESULTS-FAILURE";